[package]
name = "rhttp"
version = "0.3.1"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
# byteorder = "1.3"
url = "2.1"
native-tls ="0.2"